### ISSUE TITLE
Shake to send feedback is never consistant.

### ISSUE THREAD

**Issue by alessio-dev2rights** [testfairy/testers-app-android#3]
Hi Testfairy staff,
we are using Testfairy sdk to handle and monitor bugs on our Android platform (compile 'testfairy:testfairy-android-sdk:1.+@aar'). 
Now is more than 8 months that we use Testfairy and we have found that on Android platform the shake to send feedback is not always 100% efficient. We would like to improve this Testfairy testing phase and make our tester happy to use Testfairy.
Is there something that we need to do to make the feedback more consistent? Have you encountered this problem so far?
Thanks

**Comment by giltsl** [comment]
Hi @alessio-dev2rights 
I am very glad you are using TestFairy,
I would like to have more information about the issue you have.
Is it happens on yours device, Is it something you can reproduce?
It will be perfect if you can point me into a specific TestFairy session that have the issue.

By the way, this repo has nothing to do with the TestFairy android SDK, 
It will be more convenient if you will contact as at support@testfairy.com

**Comment by alessio-dev2rights** [comment]
Ok Thanks I'll send an email as soon as possible.
Thanks
