### ISSUE TITLE
Getting 403 disallowed_useragent error when logging into Android app.

### ISSUE THREAD

**Issue by hybridremix** [testfairy/testers-app-android#4]
_Sorry if I'm in the wrong place. This *appears* to my untrained eye to be the repo for the Android app, so I'm posting it here. Please redirect me if I'm in the wrong place._

When I open TestFairy [version 2.1; updated April 3rd, 2017] on my Galaxy S4 Active [AT&T service; Lollipop 5.0.1] and try to "sign in with Google", I immediately get an error that says:

> **403**. That's an error.
> &nbsp;
> **Error: disallowed_useragent**
> &nbsp;
> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform to perform authorization requests in the browser.

I can't find a single thing while googling for a solution about anyone else seeing this problem in TestFairy. I can't imagine I'm the only person seeing this if it's a problem with TestFairy, but I don't see anything anywhere describing a solution for an end-user. Everything I'm reading indicates this problem comes from an app not being updated to match a relatively new Google policy for OAuth requests.

I am able to log in with Google using Chrome, but I just can't seem to do it in the app. This matches the error message's description of the problem.

We were planning to use TestFairy to beta test our app so this is a serious hindrance to our deployment testing since I'm the only guy on the team with an Android device.

**Comment by giltsl** [comment]
Hey @hybridremix, I am checking it

**Comment by yuvalgo909** [comment]
In the meanwhile please browse to app.testfairy.com from your mobile.
You can also use email invitations
Thanks.
